name: Deploy Docs

on:
  push:
    branches: [master]


permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen graphviz
          pip install sphinx breathe furo

      - name: Build documentation
        working-directory: ./docs
        run: |
          sphinx-build -b html . _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          force_orphan: true